# Generated by Django 2.1.5 on 2021-10-31 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.FloatField(default=100.55, null=True)),
                ('image', models.FileField(null=True, upload_to='static/uploads')),
                ('text', models.TextField(max_length=200, null=True)),
            ],
        ),
    ]
